// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaxNdvdn8MhoWkEZTh9vObYBIZ6pj5McI',
    appId: '1:533683400832:web:1b40e8ff6409df5048b665',
    messagingSenderId: '533683400832',
    projectId: 'klinikapp-d9a68',
    authDomain: 'klinikapp-d9a68.firebaseapp.com',
    storageBucket: 'klinikapp-d9a68.appspot.com',
    measurementId: 'G-P5YVTPKY2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRy4sR-fUV8Rpzld_HpTm2UNmrw8D1Oc0',
    appId: '1:533683400832:android:a0626dc019b3a57f48b665',
    messagingSenderId: '533683400832',
    projectId: 'klinikapp-d9a68',
    storageBucket: 'klinikapp-d9a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkTRIXK5IsXIhbaOopmxeu5Gl4PJIqpFQ',
    appId: '1:533683400832:ios:a226e8c17bfcfc9048b665',
    messagingSenderId: '533683400832',
    projectId: 'klinikapp-d9a68',
    storageBucket: 'klinikapp-d9a68.appspot.com',
    iosBundleId: 'com.example.klinikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkTRIXK5IsXIhbaOopmxeu5Gl4PJIqpFQ',
    appId: '1:533683400832:ios:a226e8c17bfcfc9048b665',
    messagingSenderId: '533683400832',
    projectId: 'klinikapp-d9a68',
    storageBucket: 'klinikapp-d9a68.appspot.com',
    iosBundleId: 'com.example.klinikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaxNdvdn8MhoWkEZTh9vObYBIZ6pj5McI',
    appId: '1:533683400832:web:bcd2f595850d5e4548b665',
    messagingSenderId: '533683400832',
    projectId: 'klinikapp-d9a68',
    authDomain: 'klinikapp-d9a68.firebaseapp.com',
    storageBucket: 'klinikapp-d9a68.appspot.com',
    measurementId: 'G-TV3S63NSQ3',
  );
}
